#define WIFI_SSID "Personal-661"
#define WIFI_PASSWORD "0018781896"
#define API_KEY "AIzaSyDm52J6WTHvZyqRU4czpy5lYyuZ0TVykLQ"
#define DATABASE_URL "https://srpapa-database-default-rtdb.firebaseio.com/"
#define USER_PATH "/user"